name: transf

dependencies:
  - aiohappyeyeballs
  - aiohttp
  - aiosignal
  - async-timeout
  - attrs
  - audioread
  - certifi
  - cffi
  - charset-normalizer
  - click
  - datasets
  - decorator
  - dill
  - docker-pycreds
  - evaluate
  - filelock
  - frozenlist
  - fsspec
  - gitdb
  - GitPython
  - huggingface-hub
  - idna
  - Jinja2
  - joblib
  - lazy_loader
  - librosa
  - lightning
  - lightning-utilities
  - llvmlite
  - MarkupSafe
  - mpmath
  - msgpack
  - multidict
  - multiprocess
  - networkx
  - numba
  - numpy
  - packaging
  - pandas
  - platformdirs
  - pooch
  - protobuf
  - psutil
  - pyarrow
  - pycparser
  - python-dateutil
  - pytorch-lightning
  - pytz
  - PyYAML
  - regex
  - requests
  - safetensors
  - scikit-learn
  - scipy
  - sentry-sdk
  - setproctitle
  - six
  - smmap
  - soundfile
  - soxr
  - sympy
  - threadpoolctl
  - tokenizers
  - torch
  - torchmetrics
  - tqdm
  - transformers
  - typing_extensions
  - tzdata
  - urllib3
  - wandb
  - xxhash
  - yarl